
export const URL = "https://petalchat-cloned-imanjithreddy.c9users.io/";

export const NEARBY_POSTS_RECEIVED = "NEARBY_POSTS_RECEIVED";
export const POPULAR_POSTS_RECEIVED = "POPULAR_POSTS_RECEIVED";
export const LATEST_POSTS_RECEIVED = "LATEST_POSTS_RECEIVED";


export const NEARBY_USERS_RECEIVED = "NEARBY_USERS_RECEIVED";
export const ALL_USERS_RECEIVED = "ALL_USERS_RECEIVED";
export const POST_LIKED = "POST_LIKED";
export const POST_UNLIKED = "POST_UNLIKED";
export const LATEST_POSTS_LOADING = "LATEST_POSTS_LOADING"
export const LATEST_POSTS_REFRESH = "LATEST_POSTS_REFRESH";
export const LATEST_POSTS_INCREMENT = "LATEST_POSTS_INCREMENT";
export const CREATE_CHAT_ROOM = "CREATE_CHAT_ROOM";
export const ALL_CHAT_INCREMENT = "ALL_CHAT_INCREMENT";
export const ALL_CHAT_LOADING = "ALL_CHAT_LOADING";
export const ALL_CHAT_REFRESH = "ALL_CHAT_REFRESH";
export const ALL_CHATS_RECEIVED = "ALL_CHATS_RECEIVED";
export const CHAT_TRANSFERRED = "CHAT_TRANSFERRED";
export const CHAT_RECEIVED = "CHAT_RECEIVED";
export const REVEALED_CHATS_RECEIVED = "REVEALED_CHATS_RECEIVED";
export const GROUPS_CHATS_RECEIVED = "GROUPS_CHATS_RECEIVED";
export const OTHER_USER_RECEIVED = "OTHER_USER_RECEIVED";

export const USER_POSTS_RECEIVED = "USER_POSTS_RECEIVED";
export const USER_DETAILS_RECEIVED = "USER_DETAILS_RECEIVED";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";
export const USER_LOCATION_RECEIVED = "USER_LOCATION_RECEIVED";
export const USER_LOCATION_ERROR = "USER_LOCATION_ERROR";
export const USER_FOLLOWED = "USER_FOLLOWED";
export const USER_UNFOLLOWED = "USER_UNFOLLOWED";
export const REMOVE_USER_DETAILS = "REMOVE_USER_DETAILS";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const REMOVE_AUTH_TOKEN = "REMOVE_AUTH_TOKEN";
export const JWT_TOKEN = "JWT_TOKEN";
export const FACEBOOK_LOGIN_FAIL = "FACEBOOK_LOGIN_FAIL";
export const ERROR_AUTH_TOKEN = "ERROR_AUTH_TOKEN";


export const SET_CONTENT = "SET_CONTENT";
export const SELECT_LIBRARY_IMAGE = "SELECT_LIBRARY_IMAGE";
export const SELECT_RANDOM_IMAGE = "SELECT_RANDOM_IMAGE";
export const SET_RANDOM_IMAGE = "SET_RANDOM_IMAGE"
export const SET_LIBRARY_IMAGE = "SET_LIBRARY_IMAGE";
export const RANDOM_IMAGE_LOADING = "RANDOM_IMAGE_LOADING";
export const RANDOM_IMAGES_LOADING = "RANDOM_IMAGES_LOADING";
export const LIBRARY_IMAGE_LOADING = "LIBRARY_IMAGE_LOADING";
export const DEVICE_AUTH_URL = `${URL}nativeAuth/device`;

